apiVersion: v1
kind: Secret
metadata:
  name: acr-secret
  namespace: {{ .Values.global.namespace }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ include "lbg-app.acrCredentials" . }}
