{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.ingress.name | default (printf "%s-ingress" (include "lbg-app.fullname" .)) }}
  namespace: {{ .Values.global.namespace }}
  labels:
    app: lbg-app
    environment: {{ .Values.global.environment }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "30"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "30"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "30"
spec:
  ingressClassName: {{ .Values.ingress.className }}
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: /health
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.patientService.name }}
                port:
                  number: {{ .Values.patientService.port }}
          - path: /patients
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.patientService.name }}
                port:
                  number: {{ .Values.patientService.port }}
          - path: /appointments
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.appointmentService.name }}
                port:
                  number: {{ .Values.appointmentService.port }}
{{- end }}
