{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: lbg-app-ingress
  namespace: {{ .Values.global.namespace }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  ingressClassName: {{ .Values.ingress.className }}
  rules:
  {{- range .Values.ingress.hosts }}
  - host: {{ .host }}
    http:
      paths:
      {{- range .paths }}
      - path: {{ .path }}
        pathType: {{ .pathType }}
        backend:
          service:
            name: {{ if eq .path "/patients" }}{{ $.Values.patientService.name }}
            {{- else if eq .path "/appointments" }}{{ $.Values.appointmentService.name }}
            {{- else if eq .path "/health" }}{{ $.Values.patientService.name }}
            {{- else }}{{ $.Values.patientService.name }}{{- end }}
            port:
              number: {{ if eq .path "/patients" }}{{ $.Values.patientService.port }}
              {{- else if eq .path "/appointments" }}{{ $.Values.appointmentService.port }}
              {{- else if eq .path "/health" }}{{ $.Values.patientService.port }}
              {{- else }}{{ $.Values.patientService.port }}{{- end }}
      {{- end }}
  {{- end }}
{{- end }}
