apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: lbg-app-ingress
  namespace: lbg-ns
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "30"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "30"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "30"
spec:
  ingressClassName: nginx
  rules:
  - host: lbg-app.dev.local
    http:
      paths:
      - path: /health
        pathType: Prefix
        backend:
          service:
            name: patient-service
            port:
              number: 3000
      - path: /patients/?(.*)
        pathType: Prefix
        backend:
          service:
            name: patient-service
            port:
              number: 3000
      - path: /appointments/?(.*)
        pathType: Prefix
        backend:
          service:
            name: appointment-service
            port:
              number: 3001
