apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: lbg-app-ingress
  namespace: lbg-ns
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  ingressClassName: nginx
  rules:
  - host: lbg-app.dev.local
    http:
      paths:
      - path: /patients
        pathType: Prefix
        backend:
          service:
            name: patient-service
            port:
              number: 3000
      - path: /appointments
        pathType: Prefix
        backend:
          service:
            name: appointment-service
            port:
              number: 3001
      - path: /health
        pathType: Prefix
        backend:
          service:
            name: patient-service
            port:
              number: 3000
