apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.patientService.name }}
  namespace: {{ .Values.global.namespace }}
  labels:
    app: {{ .Values.patientService.name }}
    environment: {{ .Values.global.environment }}
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "false"
spec:
  selector:
    app: {{ .Values.patientService.name }}
  ports:
    - port: {{ .Values.patientService.servicePort }}
      targetPort: {{ .Values.patientService.port }}
      protocol: TCP
      name: http
  type: {{ .Values.patientService.serviceType }}
