global:
  namespace: lbg-ns
  environment: dev

image:
  registry: acrkamaldemodev.azurecr.io
  pullPolicy: IfNotPresent

patientService:
  name: patient-service
  replicaCount: 2
  image: patient-service
  tag: latest
  port: 3000
  serviceType: ClusterIP
  resources:
    requests:
      memory: "128Mi"
      cpu: "100m"
    limits:
      memory: "256Mi"
      cpu: "200m"
  hpa:
    minReplicas: 2
    maxReplicas: 10
    targetCPU: 50
    targetMemory: 70

appointmentService:
  name: appointment-service
  replicaCount: 2
  image: appointment-service
  tag: latest
  port: 3001
  serviceType: ClusterIP
  resources:
    requests:
      memory: "128Mi"
      cpu: "100m"
    limits:
      memory: "256Mi"
      cpu: "200m"
  hpa:
    minReplicas: 2
    maxReplicas: 10
    targetCPU: 50
    targetMemory: 70

ingress:
  enabled: true
  name: lbg-app-ingress
  className: "nginx"
  host: "lbg-app.dev.local"
